language: csharp

mono: none

dotnet: 2.0.0

services:
  - docker

script:
  - docker build -t joaopio/movie-api .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push joaopio/movie-api
