version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Movies
      - MYSQL_USER=movieapi
      - MYSQL_PASSWORD=movieapi1234
    networks:
      - movieapinetwork
  movieapi:
    build: .
    image: movie-api
    depends_on:
      - mysql
    environment:
      - DB_SERVER=mysql
      - DB_NAME=Movies
      - DB_USER=movieapi
      - DB_PASS=movieapi1234
    networks:
      - socialnetwork
      - movieapinetwork
networks:
  socialnetwork:
    external: true
  movieapinetwork:
